name: NPM Publish

on:
  push:
    branches: [master]

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PUSH_TOKEN }}

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: .nvmrc

      - name: Install
        run: yarn --immutable

      - name: Test
        run: yarn test

      - name: Build
        run: yarn build

      - name: Release
        uses: codfish/semantic-release-action@v1
        id: semantic
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
